### ISSUE TITLE
pg:copy Cannot read property 'started_at' of undefined

### ISSUE THREAD

**Issue by ransombriggs** [heroku/heroku-pg#57]
```
-> % heroku pg:copy rbriggs-pg-copy-source::DATABASE_URL DATABASE_URL -a rbriggs-pg-copy-dest 
 ▸    WARNING: Destructive action
 ▸    This command will remove all data from DATABASE
 ▸    Data from DATABASE will then be transferred to DATABASE
 ▸    To proceed, type rbriggs-pg-copy-dest or re-run this command with --confirm rbriggs-pg-copy-dest

> rbriggs-pg-copy-dest
Starting copy of DATABASE to DATABASE... done
Copying... !
 ▸    Cannot read property 'started_at' of undefined
TypeError: Cannot read property 'started_at' of undefined
    at /Users/rbriggs/src/github.com/heroku/heroku-pg/lib/pgbackups.js:95:27
    at throw (native)
    at onRejected (/Users/rbriggs/src/github.com/heroku/heroku-pg/node_modules/co/index.js:81:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by ransombriggs** [comment]
@dickeyxxx this is probably because of a `<-- 500 Internal Server Error` which I do not get with the old Ruby code
